---
# Building block config
# -----------------------------------------------------------------------------
## Specifies the name of the building block
bb_name: ics-dm-cli
bb_registry_name: icsdm.azurecr.io

## Specifies insecure docker registries, format "host:port" or "ip:port"
bb_insecure_registries: ["registry:5000"]
## Specify if 'latest' tags are built for `git_branch`
bb_release_as_latest: true

# Git config
# -----------------------------------------------------------------------------
## Specify the git repository to work with
git_source: git@github.com:ICS-DeviceManagement/ics-dm-cli.git
git_branch: main
default_branch: main

## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false
